FROM node:16-alpine AS build
ENV NODE_ENV production

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install -g npm@8.6.0 --silent
RUN npm install -g react-scripts@latest --silent
RUN npm install

COPY . .

RUN npm run build


FROM nginx:stable-alpine as production
ENV NODE_ENV production

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
